---
- hosts: all
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Backup a virtual domain.
    fortios_monitor:
     access_token: "{{ access_token }}"
     selector: 'backup.system.config'
     vdom: 'root'
     params:
         scope: 'global'
    register: backupinfo

  - name: Save the backup information.
    copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './local.backup'
